# --- general settings ---
confirm_os_window_close 0
macos_show_window_title_in none
window_padding_width 0 4 2 4


# --- shell ---
shell /opt/homebrew/bin/fish



# --- cursor ---
shell_integration  no-cursor
cursor_shape block
cursor_blink_interval 0


# --- font ---
font_family             Maple Mono Normal NF Light
bold_font               auto
italic_font             auto
bold_italic_font        auto
font_size               14


# --- theme: tokyo night ---
background #1a1b26
foreground #c0caf5
selection_background #283457
selection_foreground #c0caf5
url_color #73daca
cursor #c0caf5
cursor_text_color #1a1b26

# tabs
active_tab_background #7aa2f7
active_tab_foreground #16161e
inactive_tab_background #292e42
inactive_tab_foreground #545c7e
#tab_bar_background #15161e

# windows
active_border_color #7aa2f7
inactive_border_color #292e42

# normal
color0 #15161e
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6

# bright
color8  #414868
color9  #ff899d
color10 #9fe044
color11 #faba4a
color12 #8db0ff
color13 #c7a9ff
color14 #a4daff
color15 #c0caf5

# extended colors
color16 #ff9e64
color17 #db4b4b

# macos
macos_titlebar_color background
