# --- list of plugins ---
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"

set -g @plugin "tmux-plugins/tmux-battery"

set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin 'tmux-plugins/tmux-continuum'


# --- general settings ---
set -g default-shell "/opt/homebrew/bin/fish"
set -g default-terminal "tmux-256color"
set -g mouse "on"
set -g base-index "1"
setw -g pane-base-index "1"
set -g renumber-windows "on"
set-option -g allow-rename "off"


# --- keybindings ---
# prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# configuration reload
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# new window
unbind c
bind-key c command-prompt -p "name:" "new-window -n '%%'"

# new session
bind-key S command-prompt -p "name:" "new-session -s '%%'"

# popup bottom
bind-key B display-popup -E -w 96% -h 90% "btm"

# popup lazygit
bind-key G display-popup -E -w 90% -h 90% "lazygit"

# --- resurrect settings ---
set -g @resurrect-capture-pane-contents "on"
set -g @resurrect-processes "btm"


# --- continuum settings ---
set -g @continuum-save-interval "5"
set -g @continuum-restore "on"


# --- battery settings ---
set -g @batt_icon_charge_tier8 "󰁹"
set -g @batt_icon_charge_tier7 "󰂁"
set -g @batt_icon_charge_tier6 "󰁿"
set -g @batt_icon_charge_tier5 "󰁾"
set -g @batt_icon_charge_tier4 "󰁽"
set -g @batt_icon_charge_tier3 "󰁼"
set -g @batt_icon_charge_tier2 "󰁻"
set -g @batt_icon_charge_tier1 "󰁺"
set -g @batt_icon_status_charged "󰚥"
set -g @batt_icon_status_charging "󰂄"
set -g @batt_icon_status_discharging "󰂃"
set -g @batt_icon_status_unknown "󰂑"
set -g @batt_icon_status_attached "󱈑"


# --- styles ---
# colors
set -g @color_bg "#1a1b26"
set -g @color_fg "#c0caf5"
set -g @color_select "#283457"
set -g @color_green "#9ece6a"
set -g @color_yellow "#e0af68"
set -g @color_red "#f7768e"
set -g @color_current_window "#7aa2f7"

# window flag icons
set -g @icon_flag_last " 󰖰"
set -g @icon_flag_current " 󰖯"
set -g @icon_flag_zoom " 󰁌"
set -g @icon_flag_mark " 󰃀"
set -g @icon_flag_silent " 󰂛"
set -g @icon_flag_activity " 󱅫"
set -g @icon_flag_bell " 󰂞"

# general style
set -g status-style  "bg=#{@color_bg},fg=#{@color_fg}"
set -g message-style "bg=#{@color_bg},fg=#{@color_fg}"
set -g mode-style    "bg=#{@color_select},fg=#{@color_fg}"
set -gF prompt-cursor-colour "#{@color_fg}"

# status left
set -g status-left-length 100
set -g status-left "  #{?client_prefix,#[fg=#{@color_red}],#{?#{==:#{pane_mode},copy-mode},#[fg=#{@color_yellow}],#[fg=#{@color_green}]}}#S   "

# window status
set -g @flags_icon "#{?window_activity_flag,#{@icon_flag_activity},}#{?window_bell_flag,#{@icon_flag_bell},}#{?window_silence_flag,#{@icon_flag_silent},}#{?window_active,#{@icon_flag_current},}#{?window_last_flag,#{@icon_flag_last},}#{?window_marked_flag,#{@icon_flag_mark},}#{?window_zoomed_flag,#{@icon_flag_zoom},}"
set -g window-status-format "#I#{?#W, #W,}#{E:@flags_icon}"
set -g window-status-current-format "#[fg=#{@color_current_window}]#I#{?#W, #W,}#{E:@flags_icon}"
set -g window-status-separator "  │  "

# status right
set -g status-right-length 100
set -g status-right "#{?#{m/r:^(10|[0-9])#{a:37}$,#{battery_percentage}},#[fg=#{@color_red}]#{battery_icon}#[default],#{battery_icon}} #{battery_percentage}  │  "
set -ag status-right "󰃰 %a %d.%m  %H:%M  "


# --- initialize tpm ---
run "/opt/homebrew/opt/tpm/share/tpm/tpm"
